### ISSUE TITLE
Warning for missing `dosini` syntax

### ISSUE THREAD

**Issue by anboto** [wooorm/lowlight#13]
I am getting this error with `react-app-markdown-with-custom-components` example and `https://github.com/rstacruz/cheatsheets` content.

```Error: Unknown language: `dosini` is not registered
    at coreHighlight (/home/mart/workspace/react-app-markdown-with-custom-components/node_modules/lowlight/lib/core.js:159:11)
    at High.highlight (/home/mart/workspace/react-app-markdown-with-custom-components/node_modules/lowlight/lib/core.js:112:20)
    at visitor (/home/mart/workspace/react-app-markdown-with-custom-components/node_modules/rehype-highlight/index.js:54:27)
    at one (/home/mart/workspace/react-app-markdown-with-custom-components/node_modules/unist-util-visit/index.js:31:16)
    at all (/home/mart/workspace/react-app-markdown-with-custom-components/node_modules/unist-util-visit/index.js:54:25)
    at one (/home/mart/workspace/react-app-markdown-with-custom-components/node_modules/unist-util-visit/index.js:39:14)
    at all (/home/mart/workspace/react-app-markdown-with-custom-components/node_modules/unist-util-visit/index.js:54:25)
    at one (/home/mart/workspace/react-app-markdown-with-custom-components/node_modules/unist-util-visit/index.js:39:14)
    at visit (/home/mart/workspace/react-app-markdown-with-custom-components/node_modules/unist-util-visit/index.js:22:3)
    at transformer (/home/mart/workspace/react-app-markdown-with-custom-components/node_modules/rehype-highlight/index.js:26:5)
error An unexpected error occurred: "Command failed.
Exit code: 1```

**Comment by wooorm** [comment]
`dosini` is not a valid lowlight/highlight.js syntax: https://github.com/isagalaev/highlight.js/blob/master/docs/css-classes-reference.rst#language-names-and-aliases
